### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by lesliewubbel** [open-meta/om_skeleton#1]
Hey  I was checking the Skeleton does the email still work?

ERROR: could not find function "SESmail"

**Comment by TomWeishaar** [comment]
Hi - In the repository, nothing comes up when I search for SESmail.
However, there's a function called SESemail ("email", not "mail").

I don't know how your code ended up with SESmail, but try searching on that
and changing it to SESemail.

This assumes, of course, that you actually have access to Amazon's Simple
Email Service, which the SESemail function uses. The credentials.R file has
a lot more information on setting that up.

I thought I had updated this to work without Amazon SES; for demonstration
purposes it just printed the email on the screen rather than sending it.
That must have been an enhancement to the Open-Meta.app rather than to the
skeleton, however, as I don't see it in this code.

Tom

**Comment by lesliewubbel** [comment]
Thank you for the fast response. Ya I was trying to register an account on the skeleton on open meta to see if it works. I got that error, I am working on the code right now. 

you think Rstudio will implement HTTPS I noticed Rshiny or something does not have HTTPS. 

Regards, Leslie Wubbel  

Ya just close this issue its not big deal

**Comment by TomWeishaar** [comment]
When you run Shiny apps on your own computer using RStudio, one or the other provides a web server running on your own computer to get it all to work. I wouldn't expect that server to ever have HTTPS, but it's not something I know a lot about.

Closing this issue. - Tom
